
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfxecxtkwgbfeqeichij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmeGVjeHRrd2diZmVxZWljaGlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MTMxNTEsImV4cCI6MjA1NTI4OTE1MX0.1t8Ok6Z7-etahezyQpa1xZBZ753grYxj9BTVvRFeKhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    realtime: {
      channels: {
        retryIntervalMillis: 1000
      }
    }
  }
);

// Helper function to safely cast UUIDs for Supabase equality filters
export const castUUID = (id: string | undefined) => {
  if (!id) return undefined;
  return id as unknown as string;
};

