
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfxecxtkwgbfeqeichij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmeGVjeHRrd2diZmVxZWljaGlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MTMxNTEsImV4cCI6MjA1NTI4OTE1MX0.1t8Ok6Z7-etahezyQpa1xZBZ753grYxj9BTVvRFeKhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    realtime: {
      channels: {
        retryIntervalMillis: 1000
      }
    }
  }
);

// Helper function to safely cast UUIDs for Supabase equality filters
export const castUUID = (id: string | undefined) => {
  if (!id) return undefined;
  return id as string;
};

// Helper to properly type event data
export type DbEvent = Database['public']['Tables']['events']['Row'];
export type DbEventInsert = Database['public']['Tables']['events']['Insert'];
export type DbEventUpdate = Database['public']['Tables']['events']['Update'];

// Helper to properly type gear_events data
export type DbGearEvent = Database['public']['Tables']['gear_events']['Row'];
export type DbGearEventInsert = Database['public']['Tables']['gear_events']['Insert'];

// Helper for type casting Supabase query results
export function castData<T>(data: unknown): T {
  return data as T;
}
